version: 2
updates:
  #Check for npm package updates weekly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client-deadlab"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/client-swoggerslol"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5