name: Deploy
on:
  push:
    branches: [master]
permissions:
  contents: read
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load SSH key
        run: |
          mkdir -p ~/.ssh
          #write key using printf to preserve newlines
          printf "%s\n" "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # use known fingerprints instead of scanning
          echo "${{ secrets.SERVER_FINGERPRINT }}" >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.SERVER_PATH }} && 
            git pull && 
            npm i && 
            npm run build && 
            npm run docker-rebuild"